travis:
  secure:
    BINSTAR_TOKEN: UoQBIyrzHAoq+a0qUwCrYSQZeroaHb1XVXMMHXG5MRlOwIK/h+t/ZMdViwryTkzzHkPuATPugjHIPQKQnzUOgQ6zxVgKsq7rUe86hYgfEbDqzNUYkbE0dEMfSP5q67iemMbYa1ksmMEkjDRg/yqAJzRu83fKjVdSL0nPk3flcPBJ8n/wfiT2Y2I19/tz2uhH6RS5ySxxL0yeTgYFDyA0MvXHqFTj99HLRxVX/19v/6DGnyQ4k0y4SFsJRLo6l7pij5bBTRByMZYe7mcyh0k8GOAMDGnt62s/wUKyC4kXqWzkiJ28P5mxF/lYE3IkMNeuE5aYCMmrWbGxlutknVjmwDEa9lRlHlLOJpgU5tRTRjAKdMI7PgHXzk6ISymSCEBDt7A1wcjBGMWp176k9pi7KJEvuGUGHjQAZL7m6Kqzf3Tcu8pjkvcnFTdTVX05F1Yh0hlTqTzKCB+Oe2ptluml9RLJ6QIyPpgmSrpZK8SxW8xTb/RzzZDgYwcSdYFbxFQMo278X2AAJ0nFRyHOV8HgGaME7fExWF0o94vtFVdHyygFLta9zwdWpV5szITkdfE6G7yOBWv4wVS2bFkT6hwwpNPrDSitToxu7/agIC3SkPdtxT7sIBUWXwqC24H/QvDQ8THbejG6gzNsHCnfQi3vo5uSWjtUUIcxgM1PZKzeXGQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
